server:
  port: 8001

spring:
  application:
    name: jupiter-main
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
  messages:
    basename: i18n/messages
    encoding: UTF-8
  web:
    locale: zh_CN

mybatis-plus:
  mapper-locations: '[classpath*:/mapper/**/*.xml]'
  global-config:
    banner: false

sa-token:
  is-print: false
  token-name: x-jupiter-auth
  timeout: 31536000 # 一年
  token-style: simple-uuid
  is-log: true